//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreziDent
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders_services
    {
        public int id { get; set; }
        public int order_id { get; set; }
        public int service_id { get; set; }
        public string name_service { get; set; }
        public Nullable<decimal> price_service { get; set; }
    
        public virtual order order { get; set; }
        public virtual service service { get; set; }
    }
}
