//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreziDent
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PrezidentClinicEntities : DbContext
    {
        public PrezidentClinicEntities()
            : base("name=PrezidentClinicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<appointment> appointments { get; set; }
        public virtual DbSet<group_services> group_services { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<orders_services> orders_services { get; set; }
        public virtual DbSet<patient> patients { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<room> rooms { get; set; }
        public virtual DbSet<service> services { get; set; }
        public virtual DbSet<shedule> shedules { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<type_product> type_product { get; set; }
        public virtual DbSet<statuses_patient> statuses_patient { get; set; }
        public virtual DbSet<contacts_firm> contacts_firm { get; set; }
        public virtual DbSet<firm> firms { get; set; }
    }
}
