//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreziDent
{
    using System;
    using System.Collections.Generic;
    
    public partial class surgery
    {
        public int id { get; set; }
        public int room_id { get; set; }
        public int patient_id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.DateTime> date_pay { get; set; }
        public Nullable<System.DateTime> date_call { get; set; }
        public Nullable<System.DateTime> date_test { get; set; }
        public int status { get; set; }
    
        public virtual room room { get; set; }
        public virtual patient patient { get; set; }
    }
}
